apiVersion: apps/v1
kind: Deployment
metadata:
  name: starrocks-be-2
spec:
  selector:
    matchLabels:
      app: starrocks-be
  replicas: 1 
  template:
    metadata:
      labels:
        app: starrocks-be 
    spec:
      imagePullSecrets:
        - name: harbor-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cn-beijing.172.16.0.79
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - starrocks-be 
              topologyKey: "kubernetes.io/hostname"
      hostNetwork: true
      containers:
      - name: starrocks-be
        imagePullPolicy: IfNotPresent
        image: 10.150.30.17:28080/ops/starrocks-be:2.1.3
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: 2
            memory: "4Gi"
        ports:
        - containerPort: 9060
          name: be-9060
        - containerPort: 8040
          name: be-8040
        - containerPort: 9050
          name: be-9050
        - containerPort: 8060
          name: be-8060
        readinessProbe:
          tcpSocket:
            port: 9050
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9050
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: be-data
          mountPath: /starrocks/be/storage
        - name: be-log
          mountPath: /starrocks/be/log
        - name: be-conf
          mountPath: /starrocks/be/conf
      volumes:
      - name: be-conf
        configMap:
          name: starrocks
          items:
          - key: be.conf
            path: be.conf
      - name: be-data
        hostPath:
          path: /data/starrocks-be/data
      - name: be-log
        hostPath:
          path: /data/starrocks-be/log     