apiVersion: v1
kind: Service
metadata:
  name: starrocks-be
  labels:
    app: starrocks-be
spec:
  selector:
    app: starrocks-be
  ports:
  - name: be-9050
    port: 9050
    targetPort: 9050
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starrocks-be
spec:
  selector:
    matchLabels:
      app: starrocks-be
  serviceName: starrocks-be
  replicas: 3 
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: starrocks-be 
    spec:
      imagePullSecrets:
        - name: harbor-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: starrocks-be
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - starrocks-be
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: starrocks-be
        imagePullPolicy: Always
        image: 10.150.30.17:28080/ops/starrocks-be:2.1.3
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5" 
          limits:
            memory: "4Gi"
        ports:
        - containerPort: 9060
          name: be-9060
        - containerPort: 8040
          name: be-8040
        - containerPort: 9050
          name: be-9050
        - containerPort: 8060
          name: be-8060
        readinessProbe:
          tcpSocket:
            port: 9050
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9050
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: be-data
          mountPath: /starrocks/be/storage
        - name: be-log
          mountPath: /starrocks/be/log
        - name: be-conf
          mountPath: /starrocks/be/conf
      volumes:
      - name: be-conf
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      
  volumeClaimTemplates:
  - metadata:
      name: be-data
      labels: 
        app: starrocks-be
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: be-log
      labels: 
        app: starrocks-be
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi