apiVersion: v1
kind: Service
metadata:
  name: starrocks-fe
  labels:
    app: starrocks-fe
spec:
  selector:
    app: starrocks-fe
  ports:
  - name: fe-8030
    port: 8030
    targetPort: 8030
  - name: fe-9030
    port: 9030
    targetPort: 9030
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starrocks-fe
spec:
  selector:
    matchLabels:
      app: starrocks-fe
  serviceName: starrocks-fe
  replicas: 1 
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: starrocks-fe 
    spec:
      imagePullSecrets:
        - name: harbor-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: starrocks-fe
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - starrocks-fe
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: starrocks-fe
        imagePullPolicy: Always
        image: 10.150.30.17:28080/ops/starrocks-fe:2.1.3
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5" 
          limits:
            memory: "4Gi"
        env: 
        - name: JVM_OPTS
          value: -Xmx1024m
        ports:
        - containerPort: 8030
          name: fe-8030
        - containerPort: 9010
          name: fe-9010
        - containerPort: 9020
          name: fe-9020
        - containerPort: 9030
          name: fe-9030
        readinessProbe:
          tcpSocket:
            port: 9030
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9030
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: fe-data
          mountPath: /starrocks/fe/meta
        - name: fe-log
          mountPath: /starrocks/fe/log
        - name: fe-conf
          mountPath: /starrocks/fe/conf
      volumes:
      - name: fe-conf
        configMap:
          name: starrocks
          items:
          - key: fe.conf
            path: fe.conf
  volumeClaimTemplates:
  - metadata:
      name: fe-data
      labels: 
        app: starrocks-fe
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: fe-log
      labels: 
        app: starrocks-fe
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi