apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostNetwork: true
      nodeName: cn-beijing.172.16.106.16 
      containers:
      - image: postgres:14.2-alpine
        imagePullPolicy: Always
        name: postgres
        resources:
          requests:
            memory: "1Gi"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: dolphinscheduler
          - name: POSTGRES_USER
            value: root
          - name: POSTGRES_PASSWORD
            value: root
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        hostPath:
          path: /data/postgres


---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dev
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
