apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dolphinscheduler-worker
  labels:
    app: dolphinscheduler-worker
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: dolphinscheduler-worker
  serviceName: dolphinscheduler-worker
  template:
    metadata:
      labels:
        app: dolphinscheduler-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dolphinscheduler
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - dolphinscheduler-worker
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: harbor-secret
      terminationGracePeriodSeconds: 30
      containers:
      - name: dolphinscheduler-worker
        image: apache/dolphinscheduler:2.0.5
        imagePullPolicy: IfNotPresent
        args: 
          - "worker-server"  
        ports:
          - containerPort: 1234
            name: "worker-port"
          - containerPort: 50051
            name: "logger-port"      
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: ALERT_SERVER_OPTS
          value: "-Xms512m -Xmx512m -Xmn256m"
        envFrom:
          - configMapRef:
              name: dolphinscheduler-common
          - configMapRef:
              name: dolphinscheduler-worker
        resources:
          limits:
            memory: "4Gi"
            cpu: 4
          requests:
            cpu: 0.5
            memory: "2Gi"
        livenessProbe:
          exec:
            command: ["bash", "/root/checkpoint.sh", "WorkerServer"]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          exec:
            command: ["bash", "/root/checkpoint.sh", "WorkerServer"]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1


---
apiVersion: v1
kind: Service
metadata:
  name: dolphinscheduler-worker
spec:
  ports:
  - name: worker-port
    port: 1234
    targetPort: 1234
  - name: logger-port
    port: 50051
    targetPort: 50051
  selector:
    app: dolphinscheduler-worker
