apiVersion: v1
kind: Service
metadata:
  name: ignite
spec:
  selector:
    app: ignite
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: thinclient
      port: 10800
      targetPort: 10800
