apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-neo4j
  template:
    metadata:
      labels:
        app: datahub-neo4j
    spec:
      imagePullSecrets:
        - name: harbor-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: datahub-neo4j
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - datahub-neo4j
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: datahub-neo4j
        imagePullPolicy: IfNotPresent
        image: neo4j:4.2.4
        env:
        - name: NEO4J_AUTH
          value: "neo4j/datahub"
        - name: NEO4J_dbms_default__database
          value: "graph.db"
        - name: NEO4J_dbms_allow__upgrade
          value: "true"
        ports:
        - name: http-port
          containerPort: 7474
        - name: bolt-port
          containerPort: 7687
        livenessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
      volumes:    
      - name: neo4j-data
        hostPath: 
          path: /data/neo4j/
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-neo4j
spec:
  selector:
    app: datahub-neo4j
  ports:
    - name: http-port
      port: 7474
      targetPort: 7474
      protocol: TCP
    - name: bolt-port
      port: 7687
      targetPort: 7687
      protocol: TCP    
