apiVersion: batch/v1
kind: Job
metadata:
  name: datahub-mysql-setup-job
spec:
  template:
    metadata:
      labels:
        app: mysql-setup-job
    spec:
      imagePullSecrets:
        - name: harbor-secret
      restartPolicy: Never
      containers:
      - name: mysql-setup-job
        image: acryldata/datahub-mysql-setup:v0.8.34
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_USERNAME
          value: ""
        - name: MYSQL_PASSWORD
          value: ""
        - name: MYSQL_HOST
          value: ""
        - name: MYSQL_PORT
          value: '3306'
        - name: DATAHUB_DB_NAME
          value: "datahub_db"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi      